using System;

public sealed class Constants
{
    public const float AS_COST_DIAGONAL = 1.414f;
    public const float AS_COST_MULTIPLIER = 1f;
    public const float AS_COST_STRAIGHT = 1f;
    public const int AS_DIAGONAL_ALLOWED = 1;

    public Constants()
    {
        base..ctor();
        return;
    }

    public enum damageType
    {
        I_ARMOR,
        P_ARMOR,
        M_ARMOR,
        E_ARMOR,
        R_ARMOR,
        S_ARMOR
    }

    public enum gameDifficulty
    {
        DIFFICULTY_NORMAL,
        DIFFICULTY_EASY
    }

    public enum gameMode
    {
        GAME_MODE_CAMPAIGN,
        GAME_MODE_HEROIC,
        GAME_MODE_IRON
    }

    public enum heuristic
    {
        DIAGONAL,
        MANHATTAN,
        EUCLIDIAN
    }

    public enum levelStatus
    {
        LEVEL_STATUS_INACTIVE,
        LEVEL_STATUS_NEW,
        LEVEL_STATUS_NEW_OLD,
        LEVEL_STATUS_COMPLETED,
        LEVEL_STATUS_COMPLETED_NEW,
        LEVEL_STATUS_COMPLETED_BETTER
    }

    public enum levelType
    {
        LEVEL_TYPE_CAMPAIGN,
        LEVEL_TYPE_BONUS
    }

    public enum notificationType
    {
        NOTIFICATION_ENEMY_GOBLIN,
        NOTIFICATION_ENEMY_FAT_ORC,
        NOTIFICATION_POWER_REINFORCEMENT,
        NOTIFICATION_POWER_FIREBALL,
        NOTIFICATION_TIP_ARMOR,
        NOTIFICATION_TIP_ARMOR_MAGIC,
        NOTIFICATION_TIP_RALLY,
        NOTIFICATION_TIP_STRATEGY,
        NOTIFICATION_TIP_ARMOR_HARD,
        NOTIFICATION_ENEMY_WOLF_SMALL,
        NOTIFICATION_ENEMY_SHAMAN,
        NOTIFICATION_ENEMY_OGRE,
        NOTIFICATION_TOWER_LEVEL2,
        NOTIFICATION_TOWER_LEVEL3,
        NOTIFICATION_TOWER_RANGER,
        NOTIFICATION_TOWER_PALADIN,
        NOTIFICATION_ENEMY_BANDIT,
        NOTIFICATION_ENEMY_BRIGAND,
        NOTIFICATION_ENEMY_DARK_KNIGHT,
        NOTIFICATION_ENEMY_MARAUDER,
        NOTIFICATION_ENEMY_SPIDER_BIG,
        NOTIFICATION_ENEMY_SPIDER_SMALL,
        NOTIFICATION_ENEMY_SHADOW_ARCHER,
        NOTIFICATION_ENEMY_GARGOYLE,
        NOTIFICATION_ENEMY_WOLF,
        NOTIFICATION_TOWER_MUSKETEER,
        NOTIFICATION_TOWER_TESLA,
        NOTIFICATION_TOWER_SORCERER,
        NOTIFICATION_TOWER_BARBARIAN_BGF,
        NOTIFICATION_ENEMY_TROLL,
        NOTIFICATION_ENEMY_TROLL_CHAMPION,
        NOTIFICATION_ENEMY_TROLL_CHIEFTAIN,
        NOTIFICATION_ENEMY_WHITE_WOLF,
        NOTIFICATION_ENEMY_SLAYER,
        NOTIFICATION_ENEMY_YETI,
        NOTIFICATION_ENEMY_ROCKETEER,
        NOTIFICATION_ENEMY_DEMON,
        NOTIFICATION_ENEMY_DEMON_MAGE,
        NOTIFICATION_ENEMY_DEMON_IMP,
        NOTIFICATION_ENEMY_DEMON_WOLF,
        NOTIFICATION_ENEMY_NECROMANCER,
        NOTIFICATION_ENEMY_LAVA_ELEMENTAL,
        NOTIFICATION_ENEMY_SARELGAZ_SMALL,
        NOTIFICATION_ENEMY_GOBLIN_ZAPPER,
        NOTIFICATION_ENEMY_ORC_RIDER,
        NOTIFICATION_ENEMY_ORC_ARMORED,
        NOTIFICATION_ENEMY_FOREST_TROLL,
        NOTIFICATION_ENEMY_ZOMBIE,
        NOTIFICATION_ENEMY_SPIDER_ROTTEN,
        NOTIFICATION_ENEMY_SPIDER_ROTTEN_TINY,
        NOTIFICATION_ENEMY_ROTTEN_TREE,
        NOTIFICATION_ENEMY_SWAMP_THING,
        NOTIFICATION_TIP_HEROES,
        NOTIFICATION_ENEMY_RAIDER,
        NOTIFICATION_ENEMY_PILLAGER,
        NOTIFICATION_TIP_ELITE,
        NOTIFICATION_ENEMY_TROLL_SKATER,
        NOTIFICATION_ENEMY_TROLL_BRUTE,
        NOTIFICATION_ENEMY_CERBERUS,
        NOTIFICATION_ENEMY_LEGION,
        NOTIFICATION_ENEMY_FLAREON,
        NOTIFICATION_ENEMY_GULAEMON,
        NOTIFICATION_ENEMY_ROTTEN_LESSER
    }
}

